### PR TITLE
feat: add contract reference to service.

### PR DESCRIPTION
**Pull request by zoezou9**

### CODE REVIEW

**Comment by zoezou9** [comment]
test

**Comment by Xanonymous-GitHub** [comment]
Suggest add some descriptions (at least a simple sentence) to this PR.

**Review by Xanonymous-GitHub — COMMENTED** [review]
Suggest extract the contract addresses to a constant which referenced from `/src/utils/constant.js` .

Since we have deployed two main contracts, we may need to add both ABI json file which contains the `CA` field, and add both `CA` value into the `constant.js`.

**Comment by lohsuan** [comment]
I think this PR is accidently opened by other people on my branch. 
I will closed it and open the same feature by myself when it is ready to be reviewed.

**Pull request closed without merging**
